[book]
authors = ["joshxyzhimself"]
language = "en"
multilingual = false
src = "src"
title = "Full Stack"
description = "Notes notes notes."

[output.html]
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/joshxyzhimself/mdbook-template"
edit-url-template = "https://github.com/joshxyzhimself/mdbook-template/edit/main/{path}"
# cname = "mdbook-template.jxyz.co"